<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>2bde1ba8-d4fd-41f8-926b-43b5b6841e8b</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CloudinaryDotNet" Version="1.29.2"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.14"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.12"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.14">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Moji.BusinessLogic\Moji.BusinessLogic.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Models\Users\"/>
    </ItemGroup>

</Project>
